"""Add prep_time and cook_time to Recipe model

Revision ID: d3f465738c82
Revises: 289ae3b5503b
Create Date: 2025-12-30 16:38:26.064691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f465738c82'
down_revision = '289ae3b5503b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cook_time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('cook_time')
        batch_op.drop_column('prep_time')

    # ### end Alembic commands ###
